services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=scanserve'
      - 'POSTGRES_PASSWORD=scanserve'
      - 'POSTGRES_USER=scanserve'
    ports:
      - '5432:5432'
